config/routes.rb
SocialThingamajig::Application.routes.draw do

  get "/log_in" => "session#new"
  post "/log_in" => "session#create"
  delete "/log_out" => "session#destroy"

  get "/feed" => "posts#index"

  resources :users
  resources :friend_circles
  resources :posts

end

app/models/friend_circle.rb
class FriendCircle < ActiveRecord::Base
  attr_accessible :category_name, :creator_id,
                  :friendships_attributes, :friend_ids

  belongs_to :creator, class_name: 'User'
  has_many :friendships
  has_many :friends, through: :friendships
  has_many :post_shares

  accepts_nested_attributes_for :friendships

end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  attr_accessible :friend_circle_id, :friend_id

  belongs_to :friend, class_name: 'User'
  belongs_to :friend_circle

end

app/models/link.rb
class Link < ActiveRecord::Base
  attr_accessible :post_id, :url
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :author_id, :body, :title,
                  :post_shares_attributes, :links_attributes

  belongs_to :author, class_name: 'User'
  has_many :links
  has_many :post_shares

  accepts_nested_attributes_for :post_shares
  accepts_nested_attributes_for :links, :reject_if => :all_blank
end

app/models/post_share.rb
class PostShare < ActiveRecord::Base
  attr_accessible :friend_circle_id, :post_id
  belongs_to :post
  belongs_to :friend_circle

end

app/models/user.rb
require 'BCrypt'

class User < ActiveRecord::Base

  attr_accessible :username, :password, :posts_attributes

  validates_presence_of :username

  has_many :friend_circles, foreign_key: :creator_id
  has_many :friends, through: :friend_circles

  has_many :friendships, foreign_key: :friend_id
  has_many :within_circles, through: :friendships, source: :friend_circle
  has_many :feed_shares, through: :within_circles, source: :post_shares
  has_many :feed_posts, through: :feed_shares, source: :post


  has_many :posts, foreign_key: :author_id

  accepts_nested_attributes_for :posts


  def password=(password)
    self.password_digest = BCrypt::Password.create(password)
  end

  def validate_password(password)
    BCrypt::Password.new(self.password_digest) == password
  end

  def set_session_token!
    self.session_token = SecureRandom.base64(16)

    self.save!

    self.session_token
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include ApplicationHelper

end

app/controllers/friend_circles_controller.rb
class FriendCirclesController < ApplicationController

  def new
    @users = User.all
  end

  def create
    @fc = FriendCircle.new(params[:friend_circle])
    if @fc.save
      redirect_to friend_circles_url
    else
      render :new
    end
  end

  def edit
    @users = User.all
    @friend_circle = FriendCircle.find(params[:id])
  end

  def update
    @friend_circle = FriendCircle.find(params[:id])
    if @friend_circle.update_attributes(params[:friend_circle])
      redirect_to @friend_circle
    else
      render :edit
    end
  end

  def destroy

  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @feed_posts = current_user.feed_posts
  end

  def new
    @friend_circles = current_user.friend_circles
  end

  def create
    @post = Post.new(params[:post])
    if @post.save
      redirect_to posts_url
    else
      render :new
    end
  end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  def new

  end

  def create
    @user = User.find_by_username(params[:user][:username])
    if @user.validate_password(params[:user][:password])
      session[:session_token] = @user.set_session_token!
      redirect_to users_url
    else
      render :new
    end
  end

  def destroy
    current = current_user
    current.session_token = nil
    current.save
    session[:session_token] = nil
    redirect_to log_in_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to users_url
    else
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_user
    if token = session[:session_token]
      @current_user ||= User.find_by_session_token(token)
    else
      nil
    end
  end

  def logged_in?
    !!current_user
  end

  def authorize_user
    redirect_to log_in_url unless logged_in?
  end
end

app/helpers/friend_circles_helper.rb
module FriendCirclesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/friend_circles/edit.html.erb
<h1>Edit a Friend Circle </h1>

<form action="<%= friend_circle_url %>" method="post">
	<input type="hidden" name="_method" value="put">
	<input type="hidden" name="authenticity_token"
		value="<%= form_authenticity_token %>">
		<input type="hidden" name="friend_circle[creator_id]" value="<%= 				current_user.id %>">

		<label for="name">Friend Circle Name:</label>
		<input type="text" name="friend_circle[category_name]" id="name"
			value="<%= @friend_circle.category_name %>"><br>
		<%@users.each do |friend|%>

		<label 				for="friendships_attributes_<%=friend.id%>"><%=friend.username%></label>
		<input type="checkbox" 				name="friend_circle[friendships_attributes][<%=friend.id%>][friend_id]" 			 id="friendships_attributes_<%= friend.id%>" value="<%=friend.id%>"
				<%= "checked" if @friend_circle.friends.include?(friend)%> >
	<br>
	<%end%>

	<input type="hidden" name="friend_circle[friend_ids]" value="">



	<br>
	<input type="submit" value="Submit Changes">
</form>

app/views/friend_circles/new.html.erb
<h1>Create a Friend Circle </h1>

<form action="<%= friend_circles_url %>" method="post">
	<input type="hidden" name="authenticity_token"
		value="<%= form_authenticity_token %>">
		<input type="hidden" name="friend_circle[creator_id]" value="<%= 				current_user.id %>">

		<label for="name">Friend Circle Name:</label>
		<input type="text" name="friend_circle[category_name]" id="name"><br>
		<%@users.each do |friend|%>

		<label 				for="friendships_attributes_<%=friend.id%>"><%=friend.username%></label>
		<input type="checkbox" 				name="friend_circle[friendships_attributes][<%=friend.id%>][friend_id]" 			 id="friendships_attributes_<%= friend.id%>" value="<%=friend.id%>">
	<br>
	<%end%>

	<input type="hidden" name="friend_circle[friend_ids]" value="">

	<br>
	<input type="submit" value="Create Friend Circle">
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SocialThingamajig</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

	<% if logged_in? %>
		Logged in as: <%= current_user.username %>
		<%= button_to "Log Out", log_out_url, method: :delete %>
	<% else %>
		Log in: <%= link_to "Log In", log_in_url %>
		Sign Up: <%= link_to "Sign Up", new_user_url %>
	<% end %>

<%= yield %>

</body>
</html>

app/views/posts/index.html.erb
<h1> This is your Epic Feed (developed by Patrick & Sol)</h1>

<% @feed_posts.each do |post|%>
<li>
	<%=post.title%>
	<br>
	<%=post.body%>
	<br>
	<%=post.author.username%>
	<br>
	<ul>
	<%post.links.each do |link|%>
	<li>
		<%=link.url%>
	</li>
	<%end%>
</ul>
</li>
<%end%>

app/views/posts/new.html.erb
<h1> New Post!</h1>

<form action="<%= posts_url%>" method="post">
<input type="hidden" name="authenticity_token" value="form_authenticity_token">
<label for="title">Post Title</label>
<input type="text" name="post[title]" id="title"><br>
<label for="body">Post Body</label>
<textarea name="post[body]" id="body"></textarea><br><br>
<%@friend_circles.each do |circle|%>
	<label 				for="post_shares_attributes_<%=circle.id%>"><%=circle.category_name%></label>
	<input type="checkbox" 				name="post[post_shares_attributes][<%=circle.id%>][friend_circle_id]" 			 id="post_shares_attributes_<%= circle.id%>" value="<%=circle.id%>">
<br>
<%end%>
<% 3.times do |i| %>
	<label for="links_attributes_<%=i%>">Link:</label>
	<input type="text" name="post[links_attributes][<%=i%>][url]" 			 		id="links_attributes_<%= i%>">
<br>
<%end%>

<input type="hidden" name="post[author_id]" value="<%=current_user.id%>">

<input type="submit" value="Create Post">

</form>

app/views/session/new.html.erb
<h1>Log in</h1>

<form action="<% log_in_url %>" method="post">
	<input type="hidden" name="authenticity_token"
		value="<%= form_authenticity_token %>">

	<label for="username">Username: </label>
	<input type="text" name="user[username]">

	<label for="password">Password: </label>
	<input type="password" name="user[password]">

	<input type="submit" value="Log In">
</form>

app/views/users/index.html.erb
<% @users.each do |user| %>
	<%= user.username %>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<form action="<%= users_url %>" method="post">
	<input type="hidden" name="authenticity_token"
		value="<%= form_authenticity_token %>">

	<label for="username">Username: </label>
	<input type="text" name="user[username]"
			value="<%= @user.username if @user %>" >

	<label for="password">Password: </label>
	<input type="password" name="user[password]"
			value="<%= @user.password if @user %>" >

<h3> Your first post!</h3>

<label for="title">Post Title</label>
<input type="text" name="user[posts_attributes][0][title]" id="title"><br>
<label for="body">Post Body</label>
<textarea name="user[posts_attributes][0][body]" id="body"></textarea><br><br>
<input type="hidden" name="user[posts_attributes][0][author_id]" value="<%=User.all.length + 1%>">


<% 3.times do |i| %>
	<label for="links_attributes_<%=i%>">Link:</label>
	<input type="text" 		name="user[posts_attributes][0][links_attributes][<%=i%>][url]" 			 		id="links_attributes_<%= i%>"
	>
<br>
<%end%>



<input type="submit" value="Create User">

</form>